language: c

services:
- docker

jobs:
  include:
  # Ubuntu 14.04 doesn't support building geoclue 2.x because it requires GLib >= 2.44.0 which is hard to install
  - script: docker run ubuntu:xenial /bin/sh -c "apt-get update && apt-get build-dep --yes viking && apt-get install --yes git gtk-doc-tools libgeoclue-2-dev nettle-dev libmapnik-dev liboauth-dev && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd viking && ./autogen.sh && make -j && make -j check && make install"
  - script: docker run ubuntu:artful /bin/sh -c "apt-get update && apt-get build-dep --yes viking && apt-get install --yes git gtk-doc-tools libgeoclue-2-dev nettle-dev liboauth-dev && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd viking && ./autogen.sh && make -j && make -j check && make install"
  - script: docker run ubuntu:bionic /bin/sh -c "apt-get update && apt-get build-dep --yes viking && apt-get install --yes git gtk-doc-tools libgeoclue-2-dev nettle-dev liboauth-dev && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd viking && ./autogen.sh && make -j && make -j check && make install"
    # Further packages are installed as these are new dependencies for the latest source code, compared to the dependencies listed in the distribution version (`apt-get build-dep` always refers to the version which is built for the OS rather than the up-to-date source)
    # unclear why `sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"` is only necessary for 14.04/trusty
